# Generated by Django 5.0.4 on 2024-06-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gender_id',
            new_name='gender',
        ),
    ]
